# Redis
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
---
# NodePort
apiVersion: v1
kind: Service
metadata:
  name: {{ include "counter.fullname" . }}-svc
  labels:
    {{- include "counter.labels" . | nindent 4 }}
spec:
  #type: NodePort
  #type: LoadBalancer
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "counter.selectorLabels" . | nindent 4 }}
