---
# Redis
kind: Service
apiVersion: v1
metadata:
  name: redis-svc
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379

---
# Nodeport
kind: Service
apiVersion: v1
metadata:
  name: counter-svc
spec:
  type: NodePort
  selector:
    app: counter-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

---
# Load Balancer
kind: Service
apiVersion: v1
metadata:
  name: counter-lb
spec:
  type: LoadBalancer
  selector:
    app: counter-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

